package top.flooog.scss.entity;

import java.util.Date;

public class SelectCourse {

    private Long id;


    private String userId;

    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_course.c_name
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_course.t_name
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_course.create_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_course.update_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.id
     *
     * @return the value of select_course.id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.id
     *
     * @param id the value for select_course.id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.user_id
     *
     * @return the value of select_course.user_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.user_id
     *
     * @param userId the value for select_course.user_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.c_id
     *
     * @return the value of select_course.c_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.c_id
     *
     * @param cId the value for select_course.c_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.c_name
     *
     * @return the value of select_course.c_name
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.c_name
     *
     * @param cName the value for select_course.c_name
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.t_name
     *
     * @return the value of select_course.t_name
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.t_name
     *
     * @param tName the value for select_course.t_name
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.create_time
     *
     * @return the value of select_course.create_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.create_time
     *
     * @param createTime the value for select_course.create_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_course.update_time
     *
     * @return the value of select_course.update_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_course.update_time
     *
     * @param updateTime the value for select_course.update_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


}