package top.flooog.scss.entity;

import java.util.Date;

public class TeaCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_course.id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_course.user_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_course.c_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_course.is_select
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private Byte Selected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_course.create_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tea_course.update_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_course.id
     *
     * @return the value of tea_course.id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_course.id
     *
     * @param id the value for tea_course.id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_course.user_id
     *
     * @return the value of tea_course.user_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_course.user_id
     *
     * @param userId the value for tea_course.user_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_course.c_id
     *
     * @return the value of tea_course.c_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_course.c_id
     *
     * @param cId the value for tea_course.c_id
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_course.is_select
     *
     * @return the value of tea_course.is_select
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Byte getSelected() {
        return Selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_course.is_select
     *
     * @param Selected the value for tea_course.is_select
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setSelected(Byte Selected) {
        this.Selected = Selected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_course.create_time
     *
     * @return the value of tea_course.create_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_course.create_time
     *
     * @param createTime the value for tea_course.create_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tea_course.update_time
     *
     * @return the value of tea_course.update_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tea_course.update_time
     *
     * @param updateTime the value for tea_course.update_time
     *
     * @mbg.generated Thu Aug 20 11:30:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}