#druid
spring:
  druid:
    username: root
    password: 123456
    name: druidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scss?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 100
    initial-size: 1
    max-wait: 60000
    min-idle: 1
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 30000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 5
    max-pool-prepared-statement-per-connection-size: 20

#Mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
server:
  port: 8001
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
params: cont=countSql
